######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 3 09:41:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h widget.h
FORMS += dialog.ui widget.ui
SOURCES += dialog.cpp main.cpp widget.cpp
