#############################################################################
# Makefile for building: chanpin
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 6? 3 09:41:13 2016
# Project:  chanpin.pro
# Template: app
# Command: /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake -o Makefile chanpin.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc -lts
CXX           = arm-linux-gnueabihf-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtCore -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtNetwork -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtGui -I../../WorkDir/HW_Src/libs/qt-4.8.6/include -I. -I. -I. -I../../WorkDir/HW_Src/libs/tslib-master/include
LINK          = arm-linux-gnueabihf-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -lQtGui -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dialog.cpp \
		main.cpp \
		widget.cpp moc_dialog.cpp \
		moc_widget.cpp
OBJECTS       = dialog.o \
		main.o \
		widget.o \
		moc_dialog.o \
		moc_widget.o
DIST          = ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		chanpin.pro
QMAKE_TARGET  = chanpin
DESTDIR       = 
TARGET        = chanpin

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dialog.h ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: chanpin.pro  ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl
	$(QMAKE) -o Makefile chanpin.pro
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile chanpin.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/chanpin1.0.0 || $(MKDIR) .tmp/chanpin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/chanpin1.0.0/ && $(COPY_FILE) --parents dialog.h widget.h .tmp/chanpin1.0.0/ && $(COPY_FILE) --parents dialog.cpp main.cpp widget.cpp .tmp/chanpin1.0.0/ && $(COPY_FILE) --parents dialog.ui widget.ui .tmp/chanpin1.0.0/ && (cd `dirname .tmp/chanpin1.0.0` && $(TAR) chanpin1.0.0.tar chanpin1.0.0 && $(COMPRESS) chanpin1.0.0.tar) && $(MOVE) `dirname .tmp/chanpin1.0.0`/chanpin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/chanpin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_widget.cpp
moc_dialog.cpp: dialog.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_widget.cpp: dialog.h \
		widget.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_widget.h
ui_dialog.h: dialog.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic dialog.ui -o ui_dialog.h

ui_widget.h: widget.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp widget.h \
		dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		dialog.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

